server:
  port: '8000'

spring:
  datasource:
    # HikariCP connection pool 설정
    hikari:
      poolName: HikariPoolBooks
      minimumIdle: '1'
      maximumPoolSize: '1'
    # 오라클 클라우드 설정 : log4j 적용
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521/xe
    username: scott
    password: tiger

  #  driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #  url: jdbc:log4jdbc:oracle:thin:@localhost:1521/xe
  #  url: jdbc:log4jdbc:oracle:thin:@192.168.0.166:1521/xe
  #  url: jdbc:log4jdbc:oracle:thin:@192.168.35.172:1521/xe
  #  username: scott
  #  password: tiger

  # 자바 소스 변경시 스프링 서버 자동 재시작
  devtools:
    restart:
      enabled: 'true'

  # jpa 설정
  jpa:
    # 1) resource/data.sql 자동 실행 ( DML 실행 ), schema.sql ( ddl 실행 )
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: none
  #    ddl-auto: update
    show-sql: 'true'
    # JPA Paging 에러로 인해 버전 downgrade 함
    database-platform: org.hibernate.dialect.Oracle10gDialect
    #database-platform=org.hibernate.dialect.Oracle12cDialect
    properties:
      hibernate:
        format_sql: 'true'

  sql:
    init:
      # sql 에러 무시하고 스프링 서버 로딩
      continue-on-error: 'true'
      # 2)  resource/data.sql 자동 실행 ( DML 실행 ), schema.sql ( ddl 실행 )
      mode: always
  logging:
    level:
      org:
        hibernate: info

